name: ccs-location
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pymc>=5.0
  - arviz
  - pandas
  - numpy
  - xarray
  - pytensor
  - netcdf4
  - r-base
  - r-tidyverse
  - r-ggdist
  - r-ggtext
  - r-yaml
  - pip
  - pip:
    - snakemake
