"""
H4 country-gap decomposition table.

Quantifies how much of the Switzerland-China gap in proximity preference is
compositional (explained by the two countries having different distributions
of latent values) versus residual/direct.

For each attr_vicinity level, per posterior draw:
  gap_direct = value_switzerland - value_china   (posteriors_country.csv:
               beta + gamma, i.e. the direct country effect only)
  gap_total  = value_switzerland - value_china   (posteriors_country_total.csv:
               beta + gamma + indirect, i.e. direct + value-composition effect)
  pct_explained = 1 - gap_total / gap_direct     (how much the indirect/
               value-composition term narrows the direct gap)

Reports median + 89% HDI for gap_direct, gap_total, and pct_explained (the
per-draw ratio, which propagates uncertainty properly), alongside a simple
ratio-of-medians point estimate as a sanity check.

Run: python scripts/tables/country_gap_decomposition.py
Output: output/tables/country_gap_decomposition.tex
"""
import os
import numpy as np
import pandas as pd

try:
    direct_path = snakemake.input.country
    total_path  = snakemake.input.country_total
    out_path    = snakemake.output[0]
except NameError:
    direct_path = "output/data/posteriors_country.csv"
    total_path  = "output/data/posteriors_country_total.csv"
    out_path    = "output/tables/country_gap_decomposition.tex"

os.makedirs(os.path.dirname(out_path), exist_ok=True)

LEVEL_DISPLAY = {
    "attr_vicinity_another region":    "Another region",
    "attr_vicinity_your region":       "Your region",
    "attr_vicinity_your municipality": "Your municipality",
}
LEVEL_ORDER = list(LEVEL_DISPLAY.keys())


def hdi_1d(arr, prob=0.89):
    arr = np.sort(arr)
    n   = len(arr)
    k   = int(np.floor(prob * n))
    widths = arr[k:] - arr[:n - k]
    i = int(np.argmin(widths))
    return float(arr[i]), float(arr[i + k])


def load_gap(path):
    """Return {level: np.ndarray of gap draws (switzerland - china)}."""
    df = pd.read_csv(path)
    df = df[
        (df["model"] == "hybrid")
        & (df["framing"] == "average")
        & (df["level"].isin(LEVEL_ORDER))
    ]
    wide = df.pivot_table(
        index=["level", "chain", "draw"], columns="country", values="value"
    ).reset_index()
    gaps = {}
    for level in LEVEL_ORDER:
        sub = wide[wide["level"] == level]
        gaps[level] = (sub["switzerland"] - sub["china"]).to_numpy()
    return gaps


print("Loading posteriors...")
direct_gaps = load_gap(direct_path)
total_gaps  = load_gap(total_path)

# ---- build LaTeX ----

def fmt(x, dec=3):
    return f"{x:.{dec}f}"


def fmt_hdi(draws, dec=3):
    med    = np.median(draws)
    lo, hi = hdi_1d(draws)
    return f"{fmt(med, dec)} [{fmt(lo, dec)}, {fmt(hi, dec)}]"


rows = []
for level in LEVEL_ORDER:
    g_direct = direct_gaps[level]
    g_total  = total_gaps[level]

    pct_draws = 1.0 - (g_total / g_direct)
    pct_med   = np.median(pct_draws)
    pct_lo, pct_hi = hdi_1d(pct_draws)
    pct_ratio_of_medians = 1.0 - (np.median(g_total) / np.median(g_direct))

    rows.append(" & ".join([
        LEVEL_DISPLAY[level],
        fmt_hdi(g_direct),
        fmt_hdi(g_total),
        f"{fmt(100 * pct_med, 1)}\\% [{fmt(100 * pct_lo, 1)}, {fmt(100 * pct_hi, 1)}]",
        f"{fmt(100 * pct_ratio_of_medians, 1)}\\%",
    ]) + " \\\\")

L = []
L.append("% Generated by scripts/tables/country_gap_decomposition.py")
L.append("% Requires: booktabs")
L.append("")
L.append("\\begin{table}")
L.append("\\centering")
L.append("\\caption{H4: Switzerland--China gap in proximity preference, direct vs. "
          "total (direct + value-composition) effect. "
          "Gap = Switzerland $-$ China; median and 89\\% HDI across posterior draws. "
          "\\% explained is the per-draw reduction $1 - \\text{gap}_\\text{total} / "
          "\\text{gap}_\\text{direct}$; ratio-of-medians is a point-estimate sanity check.}")
L.append("\\label{tab:country_gap_decomposition}")
L.append("\\begin{tabular}{lllll}")
L.append("\\toprule")
L.append("Proximity level & Direct gap & Total gap & \\% explained (median [HDI]) "
         "& \\% explained (ratio of medians) \\\\")
L.append("\\midrule")
L.extend(rows)
L.append("\\bottomrule")
L.append("\\end{tabular}")
L.append("\\end{table}")

output = "\n".join(L)
with open(out_path, "w") as f:
    f.write(output + "\n")
print(f"Saved: {out_path}")
